modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="piseks_storage_tower"
version="1.0"
displayName="Pisek's Storage Tower"
credits="Simple storage system"
displayURL="https://mcreator.net"
authors="Písek Pískovec"

[[dependencies.piseks_storage_tower]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




