modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="piseks_storage_tower"
version="1.1.1"
displayName="Pisek's Storage Tower"
credits="Simple storage system"
displayURL="https://github.com/Piseks-Mods/Storage-Tower"
logoFile="logo.png"
authors="Písek Pískovec"
description='''Simple storage system'''

[[dependencies.piseks_storage_tower]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




